In [65]:
import jax
import jax.numpy as jnp
import chex
from functools import partial
from utils import tree_slice
from ipd_squared import IPDSquaredGenerator, IPDSquared

In [66]:
def unpack(state) -> None:
    for k,t in list(zip(state.keys(), state.to_tuple())):
        print(k)
        print(t)
        print("\n")

In [67]:
key = jax.random.key(0)

In [68]:
generator = IPDSquaredGenerator()
env_config = {
    "epsilon_min": -0.1,
    "epsilon_max": 0.1,
    "scaling_factor": 100,
}
env = IPDSquared(generator, **env_config)
state, timestep = env.reset(key)
unpack(state)
unpack(timestep)

power
[[0.5 0.5]
 [0.5 0.5]]


history
[-1 -1 -1 -1]


step_count
0


action_mask
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


key
Array((), dtype=key<fry>) overlaying:
[0 0]


step_type
0


reward
[0. 0. 0. 0.]


discount
1.0


observation
Observation(agents_view=Array([ 0.5,  0.5,  0.5,  0.5, -1. , -1. , -1. , -1. ],      dtype=float32, weak_type=True), action_mask=Array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]], dtype=bool))


extras
{}


