In [1]:
from typing import Optional, Sequence, Tuple
from jax_party.env import PartyEnvironment
from jax_party.env_types import Action

import jax
import jax.numpy as jnp
import chex
import itertools
from jax_party.utils import tree_slice

/home/ryanp/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
env = PartyEnvironment(1000)

key = jax.random.PRNGKey(0)
state, timestep = env.reset(key)

for actions in jnp.array(list(itertools.permutations([0, 1, 2]))):
    print("active_agents", state.active_agents)
    print("actions", actions)
    actions = env._get_valid_actions(actions, state.action_mask)
    print("corrected actions", actions)
    state, timestep = env.step(state, actions)
    print(state.cumulative_rewards, state.ranking)
    print("-" * 30)

active_agents [1 0 1]
actions [0 1 2]
corrected actions [0 0 2]
[-1.  0.  5.] [2 1 0]
------------------------------
active_agents [1 0 1]
actions [0 2 1]
corrected actions [0 0 1]
[-2.  0.  8.] [2 1 0]
------------------------------
active_agents [1 1 0]
actions [1 0 2]
corrected actions [1 0 0]
[ 1. -1.  8.] [2 0 1]
------------------------------
active_agents [1 0 1]
actions [1 2 0]
corrected actions [1 0 0]
[ 4. -1.  7.] [2 0 1]
------------------------------
active_agents [1 0 1]
actions [2 0 1]
corrected actions [2 0 1]
[ 9. -1.  7.] [0 2 1]
------------------------------
active_agents [0 1 1]
actions [2 1 0]
corrected actions [0 1 0]
[9. 2. 6.] [0 2 1]
------------------------------
